M48
; DRILL file KiCad 10.0.6 date 2026-09-09T15:26:36
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-09T15:26:36-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.700
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.000
%
G90
G05
T1
X73.5Y-55.68
X73.5Y-58.22
T2
X69.0Y-53.0
X69.0Y-55.54
X69.0Y-58.08
M30
